### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by meimosor** [apitable/widget-chart#3]
Is there a usage example for the source code of this chart? I wonder how it is used as an external package.

**Comment by arucil** [comment]
Please see the official documentation https://help.apitable.com/docs/guide/intro-widget-chart/

**Comment by meimosor** [comment]
> Please see the official documentation https://help.apitable.com/docs/guide/intro-widget-chart/

不使用widget cli的话，本地打包怎么实现？我想本地打包后传到minio手动更新
